---
- hosts: local
  connection: local
  roles:
    - digital_ocean

- hosts: production
  remote_user: root
  roles:
    # - base
    # - postgresql
    # - { role: ruby, tags: ruby, sudo: true }
    # - { role: jenkins, tags: jenkins, sudo: true }
    - { role: android, tags: android, sudo: true }
