---
- name: Create Digitial Ocean Machine
  digital_ocean: >
    state=present
    ssh_key_ids=762065
    name=osnuvem-production
    size_id=62
    region_id=4
    image_id=13089823
    backups_enabled=yes
    unique_name=yes
