- name: Add brightbox/ruby-ng repository
  apt_repository: repo='ppa:brightbox/ruby-ng'

- name: Install ruby
  apt: name={{ item }}
  with_items:
    - "ruby{{ ruby_version }}"
    - "ruby{{ ruby_version }}-dev"
    - ruby-switch